### ISSUE TITLE
Trouble with `TA_PALETTE_CLUT4` Paletted Sprites

### ISSUE THREAD

**Issue by Softdrink117** [DragonMinded/libnaomi#3]
Hiya,

I wanted to try the paletted sprites feature, but I'm having trouble getting any functional results with the 16-color palette bank and `TA_PALETTE_CLUT4` mode. 

I've tried various permutations of manually defining palettes, `INTENSITY4` and `INTENSITY8` image encoding, and even exporting graphics from different tools and working in different color modes.

At best, I've managed to get a single color from my manually defined palette to display, without respecting alpha or the gradation of the graphic asset.

There is an example of paletted textures and sprites in `pvrtest` and `advancedpvrtest`, but they only show the 256-color `TA_PALETTE_CLUT8` mode - and I have been able to reproduce that use case with my own sprites and palettes.

I've looked through some of the linked docs in the repo, but haven't found anything useful yet.

I'd really appreciate anything to point me in the right direction.

Thanks very much!

**Comment by DragonMinded** [comment]
Looking at the source to texture.c it seems I only ever added texture load operations for 8 and 16 bit textures. It looks like the `IMG2C` program (`sprite.py`) handles `INTENSITY4` just fine so that won't need upgrading. However, given there's no texture loading happening (and the various malloc examples assume texture loading works) it's not surprising you're seeing a solid color. Let me take a peek at what KallistiOS is doing for 4-bit textures since the hardware docs for twizzling are so dang confusing.

**Comment by DragonMinded** [comment]
Should be fixed with 94a53ca86782bbc674ad98a84daa78b163d64ca3.

**Comment by Softdrink117** [comment]
Amazing, thanks very much!
